install: check for docker settings

diff --git a/install b/install
--- a/install
+++ b/install
@@ -53,7 +53,10 @@ EOT
 systemctl restart docker.service
 # Verify that the setting took effect: this should print
 # driver-type: io.containerd.snapshotter.v1
-docker info|grep driver-type
+if [[ -z "$(docker info|grep driver-type)" ]]; then
+  echo "ERROR: docker did not activate the containerd-snapshotter extension properly. Maybe docker is too old? Docker 24+ is required."
+  exit 1
+fi
 
 
 # We'll use docker-buildx build caches for faster project build.
